//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAKAKO_ERP_3LAYER
{
    using System;
    using System.Collections.Generic;
    
    public partial class M0005_ListMMTB
    {
        public string Code { get; set; }
        public string ACCcode { get; set; }
        public string NameEN { get; set; }
        public string NameVN { get; set; }
        public string NameJP { get; set; }
        public string Maker { get; set; }
        public string Model { get; set; }
        public string Series { get; set; }
        public string OrgCountry { get; set; }
        public Nullable<System.DateTime> ProDate { get; set; }
        public decimal Lifetime { get; set; }
        public System.DateTime StartDeprDate { get; set; }
        public Nullable<System.DateTime> EndDeprDate { get; set; }
        public Nullable<int> Result { get; set; }
        public Nullable<int> Status { get; set; }
        public string Memo { get; set; }
        public string InstDoc { get; set; }
        public string ACCDoc { get; set; }
        public string DocNo_Disposal { get; set; }
        public string ACCDoc_Disposal { get; set; }
        public Nullable<System.DateTime> DisposalDate { get; set; }
        public string DisposalMemo { get; set; }
        public string DocNo { get; set; }
        public Nullable<System.DateTime> DocDate { get; set; }
        public string EF_VendID { get; set; }
        public string SupplierID { get; set; }
        public string SupplierName { get; set; }
        public string InvNo { get; set; }
        public Nullable<System.DateTime> InvDate { get; set; }
        public Nullable<System.DateTime> ReceiptDate { get; set; }
        public Nullable<System.DateTime> ConfirmDate { get; set; }
        public string ControlDept { get; set; }
        public Nullable<int> DisposalStatus { get; set; }
        public string Column2 { get; set; }
        public string Column3 { get; set; }
        public string Column4 { get; set; }
        public string Column5 { get; set; }
    }
}
