//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAKAKO_ERP_3LAYER
{
    using System;
    using System.Collections.Generic;
    
    public partial class M0005_ListMMTBDoc3
    {
        public string DocNo { get; set; }
        public Nullable<System.DateTime> DocDate { get; set; }
        public System.DateTime MoveDate { get; set; }
        public string ControlDept { get; set; }
        public bool DocStatus { get; set; }
        public string Memo { get; set; }
        public string Column1 { get; set; }
        public string Column2 { get; set; }
        public string Column3 { get; set; }
        public string Column4 { get; set; }
        public string Column5 { get; set; }
    }
}
