//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MMTB
{
    using System;
    using System.Collections.Generic;
    
    public partial class M0005_ListMMTBLine
    {
        public string Code { get; set; }
        public string ACCcode { get; set; }
        public string NameEN { get; set; }
        public string NameVN { get; set; }
        public string NameJP { get; set; }
        public string Maker { get; set; }
        public string Model { get; set; }
        public Nullable<System.DateTime> ConfirmDate { get; set; }
        public string DocNo_Confirm { get; set; }
        public string ControlDept { get; set; }
        public string OrgUsingDept { get; set; }
        public string OrgLineCode { get; set; }
        public string OrgGroupLineACC { get; set; }
        public string OrgLineEN { get; set; }
        public string OrgProcessCode { get; set; }
        public string SourceUsingDept { get; set; }
        public string SourceLineCode { get; set; }
        public string SourceGroupLineACC { get; set; }
        public string SourceLineEN { get; set; }
        public string SourceProcessCode { get; set; }
        public string DesUsingDept { get; set; }
        public string DesLineCode { get; set; }
        public string DesGroupLineACC { get; set; }
        public string DesLineEN { get; set; }
        public string DesProcessCode { get; set; }
        public Nullable<System.DateTime> MoveDate { get; set; }
        public string DocNo_Move { get; set; }
        public string DocNo_Disposal { get; set; }
        public string ACCDoc_Disposal { get; set; }
        public Nullable<System.DateTime> DisposalDate { get; set; }
        public System.DateTime ApplyDate { get; set; }
        public Nullable<int> DisposalStatus { get; set; }
        public string InputUser { get; set; }
        public Nullable<System.DateTime> InputDate { get; set; }
        public string ConfUser { get; set; }
        public Nullable<System.DateTime> ConfDate { get; set; }
        public string Column4 { get; set; }
        public string Column5 { get; set; }
    }
}
