//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MMTB
{
    using System;
    using System.Collections.Generic;
    
    public partial class M0005_ListMMTBNoUsed
    {
        public string Code { get; set; }
        public string ACCcode { get; set; }
        public string NameEN { get; set; }
        public string NameVN { get; set; }
        public string NameJP { get; set; }
        public string Maker { get; set; }
        public string Model { get; set; }
        public string Series { get; set; }
        public string OrgCountry { get; set; }
        public Nullable<System.DateTime> ProDate { get; set; }
        public decimal Lifetime { get; set; }
        public Nullable<int> NetValue { get; set; }
        public System.DateTime StartDeprDate { get; set; }
        public Nullable<System.DateTime> EndDeprDate { get; set; }
        public string Reason { get; set; }
        public string CurStatus { get; set; }
        public string CurPlan { get; set; }
        public string Solve { get; set; }
        public string DocNo { get; set; }
        public Nullable<System.DateTime> DocDate { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public string InputUser { get; set; }
        public Nullable<System.DateTime> InputDate { get; set; }
        public string ConfUser { get; set; }
        public Nullable<System.DateTime> ConfDate { get; set; }
        public string Column5 { get; set; }
    }
}
