//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MMTB
{
    using System;
    using System.Collections.Generic;
    
    public partial class M0005_ListMMTBDoc4
    {
        public string DocNo { get; set; }
        public System.DateTime DocDate { get; set; }
        public System.DateTime FromDate { get; set; }
        public System.DateTime ToDate { get; set; }
        public bool DocStatus { get; set; }
        public string ControlDept { get; set; }
        public string InputUser { get; set; }
        public Nullable<System.DateTime> InputDate { get; set; }
        public string ConfUser { get; set; }
        public Nullable<System.DateTime> ConfDate { get; set; }
        public string Column3 { get; set; }
        public string Column4 { get; set; }
        public string Column5 { get; set; }
    }
}
